### PR TITLE
Butler 3 global commands

### PR DESCRIPTION
**Pull request by labbydev**
Testing instructions:
* Set up a project following the readme
* See if it works

For deployment users will have to update the butler.defaults.js with their repo or we will have to add an override.js

### CODE REVIEW

**Comment by labbydev** [comment]
@gleroux02 I think this should work as a makeshift solution until we find something better.

**Comment by gleroux02** [comment]
@labbydev I'm running into this error in two different test environments:

```
vagrant@butlertesting:/var/www/butlertesting.local$ npm run butler

> butlertesting.local@1.0.0 butler /var/www/butlertesting.local
> gulp --gulpfile node_modules/butler/gulpfile.js develop

[22:07:05] Working directory changed to /var/www/butlertesting.local/node_modules/butler
[22:07:08] Using gulpfile /var/www/butlertesting.local/node_modules/butler/gulpfile.js
[22:07:08] Starting 'sass'...
[22:07:08] Starting 'sculpin'...
[22:07:08] Finished 'sculpin' after 2.86 ms
[22:07:08] Starting 'watch'...
[22:07:08] Finished 'watch' after 31 ms

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Command failed: /bin/sh -c sculpin generate --watch --server --project-dir="../../styleguide/"
/bin/sh: 1: sculpin: not found

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1016:16)
    at Socket.<anonymous> (child_process.js:1184:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:484:11)

npm ERR! Linux 3.19.0-47-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "butler"
npm ERR! node v0.12.9
npm ERR! npm  v2.14.9
npm ERR! code ELIFECYCLE
npm ERR! butlertesting.local@1.0.0 butler: `gulp --gulpfile node_modules/butler/gulpfile.js develop`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the butlertesting.local@1.0.0 butler script 'gulp --gulpfile node_modules/butler/gulpfile.js develop'.
npm ERR! This is most likely a problem with the butlertesting.local package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp --gulpfile node_modules/butler/gulpfile.js develop
npm ERR! You can get their info via:
npm ERR!     npm owner ls butlertesting.local
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/butlertesting.local/npm-debug.log
```

**Comment by labbydev** [comment]
@gleroux02 do you have sculpin installed on those environments?

**Comment by labbydev** [comment]
Ok so two things that it took to get this working within the virtual environment:
* install gulp globally
* install sculpin

I'm wondering what the best way to account for these are. Should they be included in the instructions within butler or should they be included in a project/build/environment? @becw @zendoodles @mathewpeterson  @lukewertz @aCyborg @martensc @gleroux02 do you have thoughts on this?

**Comment by lukewertz** [comment]
Yes and yes!

All dependencies should be documented (so butler should identify those as dependencies, but not try to introduce them itself).

Since we plan to use butler (at least sometimes), our development environment should have the ability to address these dependencies. (Either as an optional install/configuration, or they should come as default.)

**Comment by labbydev** [comment]
@lukewertz, @aCyborg has made a PR against this PR to address the documentation issues here (https://github.com/palantirnet/butler/pull/19). I don't know if they should come as default or not. I think for now addressing the install directions within Butler's README seems like a viable option. However, I am open to other opinions.

**Comment by lukewertz** [comment]
I think that giving basic installation instructions is all that should be provided by Butler's documentation. We can talk about whether the dependencies should be on by default or not in a different venue (specifically, we should talk about it over in [the-vagrant](https://github.com/palantirnet/the-vagrant)).

**Comment by gleroux02** [comment]
@labbydev I thought I had installed sculpin. And apparently I was done with reading for the week because I looked at this error multiple times and didn't see the sculpin error.

**Comment by labbydev** [comment]
It might be something else, but it definitely tries to succeed until it gets to sculpin. And the issue is that you can have it on your host machine but that of course doesn't translate to within the vagrant. I had the same issues myself when testing this within vagrant.

**Comment by gleroux02** [comment]
@labbydev I think my issue was the number of vm's I was testing with and the state of the-build or the-vagrant when I built them. I just tested again after installing sculpin and had no issues installing and was able to work within the styleguide directory using the global commands added to the project root's package.json. So shall we merge this PR then?

For installing sculpin I know on booth we were installing with composer:
```
"sculpin/sculpin": "~2.0",
```

**Comment by labbydev** [comment]
@gleroux02 I think this is good to merge, I agree that we should list sculpin as a dependency (with instructions) but I think it's up to a particular project/lead to see _how_ it is installed on their projects

**Pull request merged**
