### PR TITLE
Butler 23 a11y

### PR DESCRIPTION
**Pull request by labbydev**
I need another set of eyes on this to see if this output makes sense for our workflow.

**right now it's important to point out that the accessibility audit runs on the test command**

## Testing Instructions
* in your project's `package.json` set the Butler dependency to this particular branch (e.g. `"butler": "palantirnet/butler#BUTLER-23-a11y"`)
* remove the `node_modules` directory if one already exists
* run `npm install` in the project root 
* If you don't already have the scripts added to your project's `package.json`, add the following code to your project's `package.json`:

  ````
  "scripts": {
    "butler": "node_modules/butler/node_modules/.bin/gulp --gulpfile node_modules/butler/Gulpfile.js",
    "develop": "node_modules/butler/node_modules/.bin/gulp --gulpfile node_modules/butler/Gulpfile.js develop",
    "tests": "node_modules/butler/node_modules/.bin/gulp --gulpfile node_modules/butler/Gulpfile.js test",
    "deploy": "node_modules/butler/node_modules/.bin/gulp --gulpfile node_modules/butler/Gulpfile.js deploy"
  },
`````
* run `npm run tests` from the project directory
* Observe that the results of the sass linting and accessibility audit appear in the console 

## Todo before merging
- [x] Add documentation (Work being done here: https://github.com/palantirnet/butler/pull/42)
- [x] npm-shrinkwrap (See https://github.com/palantirnet/butler/pull/31#issuecomment-234922488)

### CODE REVIEW

**Comment by labbydev** [comment]
Things to update before this is officially ready to be merged:
* [ ] documentation

**Comment by labbydev** [comment]
@patrickfweston can you review the feedback that comes out of this and LMK if it is helpful for you?

**Comment by patrickfweston** [comment]
@labbydev : Since we're still using old Butler on SDSU, I decided to just spin up the MCOR project and test it there. It looks like the current setup tests html files, so I compiled the styleguide and tested the output_dev directory there.

The errors/warnings given are helpful. It throws a lot of `Check that the link text combined with programmatically determined link context identifies the purpose of the link.` even when the link is described appropriately. The are just warnings, so I guess you can safely ignore them. In general, though, I think this is really helpful and a great test toward more consistent accessibility testing at Palantir.

Is there any way that this could be configured to test a couple of Drupal-specific URLs instead of the compiled HTML from the styleguide? I think it'd be really helpful if you could test some pages in Drupal (the homepage, a page content type, etc.) based on a list of URLs. 

Drupal also fixes/address a lot of these accessibility issues by default (adding the `langcode` to the HTML element for instance). Since this is where the user is going to be encountering the site, I think it makes more sense to test here rather than the styleguide (especially since some of the errors/warnings were related to the styleguide wrapping layout, not project specific code).

I'd be happy to review again, have a conversation about this, etc. Nice work! 👍

**Comment by lukewertz** [comment]
I now consider this RTBC and ready to merge.

@labbydev, who gets to push the button?

**Comment by lukewertz** [comment]
@labbydev You mention that a todo on this is "npm-shrinkwrap". Am I correct in reading that the actionable thing you meant to capture by that was "Remove npm-shrinkwrap from the repository"? If so, I believe that task is completed by this commit: https://github.com/palantirnet/butler/pull/31/commits/c638c4d3a3859c63583aa3269874221b799990db.

Is there anything else to be done on that, or can we (you) cross that off the list?

**Pull request merged**
