### PR TITLE
Singularity gs update

### PR DESCRIPTION
**Pull request by aCyborg**
This updates butler's shrinkwrap and the path to singularity.

Tested on Augustana. However when I re shrinkwrapped some of the other stuff updated too.

### CODE REVIEW

**Comment by aCyborg** [comment]
Major Shrinkwrap changes:
* ansi was replaced with amdefine

**Comment by martensc** [comment]
@aCyborg any action we need to take with the Shrinkwrap change?

**Comment by aCyborg** [comment]
@martensc I want lauren to take a look at that bit.

**Comment by labbydev** [comment]
I don't see any issues with this. The only note I would make is that if you're going to take out zen-grids you should probably take the import out of the `_init.scss` as well.

**Pull request merged**
